<h1>Bicycle</h1>
<div class="row col-md-12 centered">
    <table class="table table-striped custab">
        <thead>
        <a href="bicycles/create/" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new bicycle</a>
        <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>Year</th>
            <th>Category</th>
            <th>Gender</th>
            <th>Color</th>
            <th>Weight</th>
            <th>Condition</th>
            <th>Price</th>
            <th class="text-center">Action</th>
        </tr>
        </thead>
        <?php
        foreach ($show as $Bicycle)
        {
            echo '<tr>';
            echo "<td>" . $Bicycle->getBrand() . "</td>";
            echo "<td>" . $Bicycle->getModel() . "</td>";
            echo "<td>" . $Bicycle->getYear() . "</td>";
            echo "<td>" . $Bicycle->getCategory() . "</td>";
            echo "<td>" . $Bicycle->getStringGender() . "</td>";
            echo "<td>" . $Bicycle->getColor() . "</td>";
            echo "<td>" . $Bicycle->getWeightShow() . "</td>";
            echo "<td>" . $Bicycle->getStringCondition() . "</td>";
            echo "<td>" . $Bicycle->getPriceShow() . "</td>";
            echo "<td class='text-center'><a class='btn btn-info btn-xs' href='bicycles/edit/" . $Bicycle->getId() . "' ><span class='glyphicon glyphicon-edit'></span> Edit</a> <a href='bicycles/delete/" . $Bicycle->getId() . "' class='btn btn-danger btn-xs'><span class='glyphicon glyphicon-remove'></span> Del</a></td>";
            echo "</tr>";
        }
        ?>
    </table>
</div>